import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import Home from './page'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'IndiKart',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='nav'>
          <Navbar />

        </div>
        <div className='item_mainbody'>
          {children}
        </div>

        <div className='footer'>
          <Footer />
        </div>
      </body>
    </html>
  )
}
